### ISSUE TITLE
Talks page shows projects

### ISSUE THREAD

**Issue by HarshKapadia2** [dwvicy/poppity#1]
- The [talks page on the web site](https://dwvicy.ml/talks) shows your personal projects rather than your talks.

	<img src="https://user-images.githubusercontent.com/50140864/119571308-d5a1de80-bdce-11eb-9239-44089c3ed07b.png" width="70%" />

- I think you forgot to change the import in [./pages/talks.js (line no. 3)](https://github.com/dwvicy/poppity/blob/main/pages/talks.js#L3).

- [./src/data/talks-data.js](https://github.com/dwvicy/poppity/blob/main/src/data/talks-data.js) is empty, so maybe add a 'Work in progress' message till you've populated it?

**Comment by dwvicy** [comment]
I'm actually working on it since yesterday. I've populated talks-data.js.

**Comment by HarshKapadia2** [comment]
Okay, sure. Your portfolio does look good!

I can't see anything in `talk-data.js` though.

![image](https://user-images.githubusercontent.com/50140864/119608820-38699900-be14-11eb-8b9e-133a8ac2b06d.png)
